# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo build FirstJob
  - job: SecondJob
    steps:
    - bash: echo build SecondJob

- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployFirstJob
    steps:
    - bash: echo build DevDeployFirstJob

- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeployFirstJob
    steps:
    - bash: echo build QADeployFirstJob

- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeployFirstJob
    steps:
    - bash: echo build ProdDeployFirstJob
